[package]
name = "youtube-viewcount-logger-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "*", features = ["sqlite", "runtime-tokio"] }
tokio = { version = "*", features = ["rt", "rt-multi-thread", "macros"] }
reqwest = { version = "*" }