INSERT INTO __source__ (playlist_key, db_key, hashtag, screen_name, is_tweet) VALUES ('PLAAEA82D2950BC77D', 'モーニング娘。', 'モーニング娘25', 'モーニング娘。''25', 1);
INSERT INTO __source__ (playlist_key, db_key, hashtag, screen_name, is_tweet) VALUES ('PL0DCF7F78614F3AE6', 'アンジュルム', 'アンジュルム', 'アンジュルム', 1);
INSERT INTO __source__ (playlist_key, db_key, hashtag, screen_name, is_tweet) VALUES ('PLs8AlpdTjgwdSDETD55q0i3W98tC9SAur', 'juicejuice', 'juicejuice', 'Juice=Juice', 1);
INSERT INTO __source__ (playlist_key, db_key, hashtag, screen_name, is_tweet) VALUES ('PL8m86iV3p-nRdW2cckAwqruBKuzrxoVvW', 'BEYOOOOONDS', 'BEYOOOOONDS', 'BEYOOOOONDS', 1);
INSERT INTO __source__ (playlist_key, db_key, hashtag, screen_name, is_tweet) VALUES ('PL0XLej3y4LDmLO0FHu8HBkldiggTt1Es4', 'つばきファクトリー', 'つばきファクトリー', 'つばきファクトリー', 1);
INSERT INTO __source__ (playlist_key, db_key, hashtag, screen_name, is_tweet) VALUES ('PLHdMoq6t0XIA5JLPo-SyTTqEByvdu1cGA', 'ochanorma', 'ochanorma', 'OCHA NORMA', 1);
INSERT INTO __source__ (playlist_key, db_key, hashtag, screen_name, is_tweet) VALUES ('PLc_REKUn8hhDbzMfjnIocF-siMz7TReb4', 'rosychronicle', 'rosychronicle', 'ロージークロニクル', 1);
INSERT INTO __source__ (playlist_key, db_key, hashtag, screen_name, is_tweet) VALUES ('PLCpSIn0xlyXl0ceNf4rBZvmF2njxunqQC', 'ハロプロダンス部', 'ハロプロダンス部', 'ハロプロダンス部', 0);
INSERT INTO __source__ (playlist_key, db_key, hashtag, screen_name, is_tweet) VALUES ('PLcu1vvKzbBMk1i4k-DF3q5ii0007W-zh7', 'こぶしファクトリー', 'こぶしファクトリー', 'こぶしファクトリー', 0);
INSERT INTO __source__ (playlist_key, db_key, hashtag, screen_name, is_tweet) VALUES ('PLhDVFhoEVU3l3X0obfPzdD5OHTbnv7Oio', 'カントリー・ガールズ', 'カントリー・ガールズ', 'カントリー・ガールズ', 0);
INSERT INTO __source__ (playlist_key, db_key, hashtag, screen_name, is_tweet) VALUES ('PLCpSIn0xlyXkPMYUoVgHmj3clVnEWxSHz', 'Buono!', 'Buono', 'Buono!', 0);
INSERT INTO __source__ (playlist_key, db_key, hashtag, screen_name, is_tweet) VALUES ('PLF0E7D2433E255B81', 'Buono!', 'Buono', 'Buono!', 1);
INSERT INTO __source__ (playlist_key, db_key, hashtag, screen_name, is_tweet) VALUES ('OLAK5uy_l_xKCyQPw4uXQd3mnw0yShaZm3AOANkQI', 'Berryz工房', 'Berryz工房', 'Berryz工房', 1);
INSERT INTO __source__ (playlist_key, db_key, hashtag, screen_name, is_tweet) VALUES ('PL04DB1D3D596D47E7', '℃-ute', 'c_ute', '℃-ute', 1);
INSERT INTO __source__ (playlist_key, db_key, hashtag, screen_name, is_tweet) VALUES ('PLeUX-FlHsb-tGpXYdlTS8rjjqCLxUB-eh', '鈴木愛理', '鈴木愛理', '鈴木愛理', 1);
INSERT INTO __source__ (playlist_key, db_key, hashtag, screen_name, is_tweet) VALUES ('PLFMni9aeqKTyLxgYVGR9y7zO28Ip5q6Kb', '道重さゆみ', '道重さゆみ', '道重さゆみ', 1);
INSERT INTO __source__ (playlist_key, db_key, hashtag, screen_name, is_tweet) VALUES ('PL6A59UsSlG7ex5t5QBIbi4PPviUrZr43p', '宮本佳林', '宮本佳林', '宮本佳林', 1);
INSERT INTO __source__ (playlist_key, db_key, hashtag, screen_name, is_tweet) VALUES ('PL4CUK5GhdtMnB4ByVY_X3smojU2uY6fAB', 'PINKCRES', 'PINKCRES', 'PINK CRES.', 0);
INSERT INTO __source__ (playlist_key, db_key, hashtag, screen_name, is_tweet) VALUES ('PLCpSIn0xlyXl5zat4Nzwhd-JC5D-QR14d', 'COVERS - One on One -', 'CoversOneOnOne', 'COVERS - One on One -', 0);
INSERT INTO __source__ (playlist_key, db_key, hashtag, screen_name, is_tweet) VALUES ('PLFMni9aeqKTw_nNHBiGWfPLT-VMdMez97', 'COVERS - One on One -', 'CoversOneOnOne', 'COVERS - One on One -', 0);
INSERT INTO __source__ (playlist_key, db_key, hashtag, screen_name, is_tweet) VALUES ('PLFMni9aeqKTwHuSxF4zsHUBMwrubNI05X', 'COVERS ～The Ballad～', 'CoversTheBallad', 'COVERS ～The Ballad～', 0);
INSERT INTO __source__ (playlist_key, db_key, hashtag, screen_name, is_tweet) VALUES ('PLFMni9aeqKTzQ4ciZ-vNscbKge63ohqri', 'アプカミ・ミュージック・デリバリー', 'アプカミ・ミュージック・デリバリー', 'アプカミ・ミュージック・デリバリー', 0);
INSERT INTO __source__ (playlist_key, db_key, hashtag, screen_name, is_tweet) VALUES ('PLPHwLN81i8cqlVTlXWre1Z7daRXXoa_h_', 'ビタスイ', 'ビタスイ', 'Bitter & Sweet', 0);
INSERT INTO __source__ (playlist_key, db_key, hashtag, screen_name, is_tweet) VALUES ('PLFMni9aeqKTwRBEifr0wecspeZPZ24AEN', 'ブラザーズ5', 'ブラザーズ5', 'ブラザーズ5', 0);
INSERT INTO __source__ (playlist_key, db_key, hashtag, screen_name, is_tweet) VALUES ('PLFMni9aeqKTx6FGeICQu6AMh_h7XaiWrB', 'シャ乱Q', 'シャ乱Q', 'シャ乱Q', 0);
INSERT INTO __source__ (playlist_key, db_key, hashtag, screen_name, is_tweet) VALUES ('PLFMni9aeqKTxAMChTm-sad305266kliMy', 'LoVendoЯ', 'LoVendoЯ', 'LoVendoЯ', 0);
INSERT INTO __source__ (playlist_key, db_key, hashtag, screen_name, is_tweet) VALUES ('PLFMni9aeqKTzQ054kNN0VAn_TC8HVIPvA', '田﨑あさひ', '田﨑あさひ', '田﨑あさひ', 0);
INSERT INTO __source__ (playlist_key, db_key, hashtag, screen_name, is_tweet) VALUES ('PLXok3xPFmG2ASK8fo_GEwdk7JQALn0P_o', '高橋愛・田中れいな・夏焼雅', '高橋愛・田中れいな・夏焼雅', '高橋愛・田中れいな・夏焼雅', 0);
INSERT INTO __source__ (playlist_key, db_key, hashtag, screen_name, is_tweet) VALUES ('PLFMni9aeqKTx6nJoI4lDcXIW0RnkIj-WC', '吉川友', '吉川友', '吉川友', 0);
INSERT INTO __source__ (playlist_key, db_key, hashtag, screen_name, is_tweet) VALUES ('PL106616353F82EF27', '中島卓偉', '中島卓偉', '中島卓偉', 0);
INSERT INTO __source__ (playlist_key, db_key, hashtag, screen_name, is_tweet) VALUES ('PLFMni9aeqKTxaQnGrEBaf20ZtWGc2FGGt', 'KAN', 'KAN', 'KAN', 0);
INSERT INTO __source__ (playlist_key, db_key, hashtag, screen_name, is_tweet) VALUES ('PLFMni9aeqKTwLp-YS0TdSAJNFp2QdF5et', 'hangryangryf', 'hangryangryf', 'HANGRY&ANGRY', 0);
INSERT INTO __source__ (playlist_key, db_key, hashtag, screen_name, is_tweet) VALUES ('PL6xCFVfh13DFK5Gsv_qy7Rlwcg_gzcf_a', '里山里海', '里山里海', 'SATOYAMA SATOUMI movement', 0);
INSERT INTO __source__ (playlist_key, db_key, hashtag, screen_name, is_tweet) VALUES ('PLFMni9aeqKTyw-UpUPRSEJtD0QfjasWhH', '松原健之', '松原健之', '松原健之', 0);
INSERT INTO __source__ (playlist_key, db_key, hashtag, screen_name, is_tweet) VALUES ('PLFMni9aeqKTz7uYHYKB-b_7SRo7dxKmeL', '上々軍団', '上々軍団', '上々軍団', 0);
INSERT INTO __source__ (playlist_key, db_key, hashtag, screen_name, is_tweet) VALUES ('OLAK5uy_m-IDdDas3oTbaeCG8B-EMeQTe7uwW0wcw', '真野恵里菜', '真野恵里菜', '真野恵里菜', 0);
INSERT INTO __source__ (playlist_key, db_key, hashtag, screen_name, is_tweet) VALUES ('OLAK5uy_mZKo1FwBv_WzjTnkYLglBj4dlWAuax3Js', '森高千里', '森高千里', '森高千里', 0);
INSERT INTO __source__ (playlist_key, db_key, hashtag, screen_name, is_tweet) VALUES ('PL59O0JbKsFLp-RYKpMhN_pooj_bJckLL7', 'アップアップガールズ(仮)', 'アプガ', 'アップアップガールズ(仮)', 0);
INSERT INTO __source__ (playlist_key, db_key, hashtag, screen_name, is_tweet) VALUES ('OLAK5uy_kFIc8YxoczUnmcpF3Cgrew3HahESCz2ls', '鞘師里保', '鞘師里保', '鞘師里保', 1);
INSERT INTO __source__ (playlist_key, db_key, hashtag, screen_name, is_tweet) VALUES ('PLFMni9aeqKTwKr8lVnRSCHFcDiQEjFB_v', '犬神サーカス団', '犬神サーカス団', '犬神サーカス団', 0);
INSERT INTO __source__ (playlist_key, db_key, hashtag, screen_name, is_tweet) VALUES ('PLFMni9aeqKTwvVpSgoB9GyIscELI5ECBr', 'つんく', 'つんく', 'つんく♂', 0);
INSERT INTO __source__ (playlist_key, db_key, hashtag, screen_name, is_tweet) VALUES ('PLXok3xPFmG2A9jkc4415xT1t_lTMyTtc3', '佐藤優樹', '佐藤優樹', '佐藤優樹', 1);
INSERT INTO __source__ (playlist_key, db_key, hashtag, screen_name, is_tweet) VALUES ('PLFMni9aeqKTwb91a6lLvQiEMNEZXpD88v', 'ハロプロ25周年記念公開MV', 'ハロプロ25周年記念公開MV', 'ハロプロ25周年記念公開MV', 1);
INSERT INTO __source__ (playlist_key, db_key, hashtag, screen_name, is_tweet) VALUES ('PLFMni9aeqKTw8G3gCcMDBUKwDCAts-Cj-', '松浦亜弥', '松浦亜弥', '松浦亜弥', 0);
INSERT INTO __source__ (playlist_key, db_key, hashtag, screen_name, is_tweet) VALUES ('PLFMni9aeqKTxpeBpkYUe4TbQ2RtFiz8hJ', '藤本美貴', '藤本美貴', '藤本美貴', 0);
INSERT INTO __source__ (playlist_key, db_key, hashtag, screen_name, is_tweet) VALUES ('PLFMni9aeqKTzwxJrS92a6zbxKQiYydGkG', '後藤真希', '後藤真希', '後藤真希', 0);
INSERT INTO __source__ (playlist_key, db_key, hashtag, screen_name, is_tweet) VALUES ('PLFMni9aeqKTxJqAbOc60917KKfOsAmjqD', '中澤裕子', '中澤裕子', '中澤裕子', 0);
INSERT INTO __source__ (playlist_key, db_key, hashtag, screen_name, is_tweet) VALUES ('PLFMni9aeqKTxNAXGrN4VW_qpYD1fLoI5H', 'メロン記念日', 'メロン記念日', 'メロン記念日', 0);
INSERT INTO __source__ (playlist_key, db_key, hashtag, screen_name, is_tweet) VALUES ('PLFMni9aeqKTzGddgeMhbXMhXgz8dMgaJs', '太陽とシスコムーン', '太陽とシスコムーン', '太陽とシスコムーン', 0);
INSERT INTO __source__ (playlist_key, db_key, hashtag, screen_name, is_tweet) VALUES ('PLXok3xPFmG2DWOqD9q7yGm608F6gNjUIx', '稲場愛香', '稲場愛香', '稲場愛香', 1);
INSERT INTO __source__ (playlist_key, db_key, hashtag, screen_name, is_tweet) VALUES ('PLXok3xPFmG2DiHcV0pWOnzcJn8wVx7jlL', '譜久村聖', '譜久村聖', '譜久村聖', 1);
INSERT INTO __source__ (playlist_key, db_key, hashtag, screen_name, is_tweet) VALUES ('PLXok3xPFmG2DsiyGQD2A5Elihz05RVIR-', 'mlinemusic', 'mlinemusic', 'M-line Music', 1);
INSERT INTO __source__ (playlist_key, db_key, hashtag, screen_name, is_tweet) VALUES ('PLFMni9aeqKTwIf7DShjl6y2Lf2-MGUvd3', 'タンポポ', 'タンポポ', 'タンポポ', 0);
INSERT INTO __source__ (playlist_key, db_key, hashtag, screen_name, is_tweet) VALUES ('PLFMni9aeqKTw00DcNa2h05AdhzJCr-eiV', 'プッチモニ', 'プッチモニ', 'プッチモニ', 0);
INSERT INTO __source__ (playlist_key, db_key, hashtag, screen_name, is_tweet) VALUES ('PLFMni9aeqKTwrRRpwWLL9U7QQqtPZaPS3', 'ミニモニ。', 'ミニモニ', 'ミニモニ。', 0);
INSERT INTO __source__ (playlist_key, db_key, hashtag, screen_name, is_tweet) VALUES ('PLHBlp1EugxwdY9abMZagocJvRfbc_gVMr', 'ME_I', 'ME_I', 'ME:I', 1);
INSERT INTO __source__ (playlist_key, db_key, hashtag, screen_name, is_tweet) VALUES ('PLCpSIn0xlyXlLr0t1-wpYgHkLt_FUfgLw', 'ME_I', 'ME_I', 'ME_I', 0);
