name: deno_docker.yml
on:
  push:
    branches: [ "master" ]
    paths:
      - 'instagram/Dockerfile'
      - '.github/workflows/deno_docker.yml'
  workflow_dispatch:

jobs:
  build-container:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: 'instagram'
          file: instagram/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/instagram-scraper:latest