name: instagram_scraper.yml
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      date:
        description: Date for the scraper to run
        required: true
        type: string

jobs:
  define_matrix:
    runs-on: ubuntu-latest
    outputs:
      accounts: ${{ steps.list_accounts.outputs.accounts }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Load cargo cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
            Cargo.lock
          key: ${{ runner.os }}-cargo-

      - name: list monitored accounts
        id: list_accounts
        run: cargo run --release --bin instagram_scraper >> $GITHUB_OUTPUT

  get_account_stats:
    needs: define_matrix
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      matrix:
        account: ${{ fromJson(needs.define_matrix.outputs.accounts) }}
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
#        with:
#          lfs: true
#      - name: get account status
#        uses: docker://ghcr.io/yayoimizuha/instagram-scraper:latest
#        with:
#          args: run --allow-all instagram/instagram_follower.ts  ${{ matrix.account }}
      - name: get account status
        uses: docker://ghcr.io/yayoimizuha/instagram-scraper:latest
        with:
          entrypoint: ln -s ~/.cache /.cache && find /github/home/.cache/ms-playwright/
