name: Migrate SQLite to DuckDB Data
on:
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Cargo cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
            Cargo.lock
          key: ${{ runner.os }}-cargo

      - name: Download save.sqlite
        run: wget https://github.com/yayoimizuha/youtube-viewcount-logger-python/raw/refs/heads/master/save.sqlite

      - name: Run migration
        run: cargo run --release --bin migrate_duckdb

      - name: Compress data
        run: zstd data.duckdb --ultra -22 -f

      - name: Commit changes
        run: |
          git lfs install
          git lfs track data.duckdb.zst
          git lfs track
          git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git config --global core.quotepath off
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git status
          git add data.duckdb.zst -f
          git commit -m "Migration from https://github.com/yayoimizuha/youtube-viewcount-logger-python/blob/master/save.sqlite"
          git push origin HEAD:${GITHUB_REF} -f


      - name: Cargo cache
        uses: actions/cache/save@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
            Cargo.lock
          key: ${{ runner.os }}-cargo