name: Generate Cargo Cache
on:
  workflow_dispatch:

jobs:
  update-cargo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate UUID
        id: uuid
        run:
          echo "uuid=$(uuidgen)" >> $GITHUB_OUTPUT


      - name: Update dependencies
        run: cargo update

      - name: build new dependencies
        run: cargo build --profile relwithdebinfo

      - name: Store cargo cache
        uses: actions/cache/save@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
            Cargo.lock
          key: ${{ runner.os }}-cargo-${{ steps.uuid.outputs.uuid }}
